/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OutletRouteImport } from './routes/outlet'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as OutletIndexRouteImport } from './routes/outlet/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ShopWishlistRouteImport } from './routes/shop/wishlist'
import { Route as ShopTermsRouteImport } from './routes/shop/terms'
import { Route as ShopShippingPolicyRouteImport } from './routes/shop/shipping-policy'
import { Route as ShopRefundPolicyRouteImport } from './routes/shop/refund-policy'
import { Route as ShopContactRouteImport } from './routes/shop/contact'
import { Route as ShopCartRouteImport } from './routes/shop/cart'
import { Route as ShopAboutRouteImport } from './routes/shop/about'
import { Route as CustomerVerifyEmailRouteImport } from './routes/customer/verify-email'
import { Route as CustomerSignUpRouteImport } from './routes/customer/sign-up'
import { Route as CustomerSignInRouteImport } from './routes/customer/sign-in'
import { Route as AdminSignInRouteImport } from './routes/admin/sign-in'
import { Route as AccountWishlistRouteImport } from './routes/account/wishlist'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as ShopProductsIndexRouteImport } from './routes/shop/products/index'
import { Route as OutletSignInIndexRouteImport } from './routes/outlet/sign-in/index'
import { Route as OutletShipmentsIndexRouteImport } from './routes/outlet/shipments/index'
import { Route as OutletSalesIndexRouteImport } from './routes/outlet/sales/index'
import { Route as OutletInventoryIndexRouteImport } from './routes/outlet/inventory/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as AdminShipmentsIndexRouteImport } from './routes/admin/shipments/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOutletsIndexRouteImport } from './routes/admin/outlets/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminOffersIndexRouteImport } from './routes/admin/offers/index'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin/inventory/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminCouponsIndexRouteImport } from './routes/admin/coupons/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as ShopProductsSlugRouteImport } from './routes/shop/products/$slug'
import { Route as AdminOutletsOutletIdRouteImport } from './routes/admin/outlets/$outletId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders.$orderId'

const DashboardUsersIndexLazyRouteImport =
  createFileRoute('/dashboard/users/')()
const DashboardSettingsNotificationsLazyRouteImport = createFileRoute(
  '/dashboard/settings/notifications',
)()
const DashboardSettingsDisplayLazyRouteImport = createFileRoute(
  '/dashboard/settings/display',
)()
const DashboardSettingsAppearanceLazyRouteImport = createFileRoute(
  '/dashboard/settings/appearance',
)()
const DashboardSettingsAccountLazyRouteImport = createFileRoute(
  '/dashboard/settings/account',
)()

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletRoute = OutletRouteImport.update({
  id: '/outlet',
  path: '/outlet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const OutletIndexRoute = OutletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutletRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ShopWishlistRoute = ShopWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ShopRoute,
} as any)
const ShopTermsRoute = ShopTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ShopRoute,
} as any)
const ShopShippingPolicyRoute = ShopShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => ShopRoute,
} as any)
const ShopRefundPolicyRoute = ShopRefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => ShopRoute,
} as any)
const ShopContactRoute = ShopContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAboutRoute = ShopAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ShopRoute,
} as any)
const CustomerVerifyEmailRoute = CustomerVerifyEmailRouteImport.update({
  id: '/customer/verify-email',
  path: '/customer/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignUpRoute = CustomerSignUpRouteImport.update({
  id: '/customer/sign-up',
  path: '/customer/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignInRoute = CustomerSignInRouteImport.update({
  id: '/customer/sign-in',
  path: '/customer/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignInRoute = AdminSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AdminRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexLazyRoute = DashboardUsersIndexLazyRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/users/index.lazy').then((d) => d.Route),
)
const ShopProductsIndexRoute = ShopProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => ShopRoute,
} as any)
const OutletSignInIndexRoute = OutletSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => OutletRoute,
} as any)
const OutletShipmentsIndexRoute = OutletShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => OutletRoute,
} as any)
const OutletSalesIndexRoute = OutletSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => OutletRoute,
} as any)
const OutletInventoryIndexRoute = OutletInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => OutletRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const AdminShipmentsIndexRoute = AdminShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOutletsIndexRoute = AdminOutletsIndexRouteImport.update({
  id: '/outlets/',
  path: '/outlets/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersIndexRoute = AdminOffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsIndexRoute = AdminCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSettingsNotificationsLazyRoute =
  DashboardSettingsNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSettingsDisplayLazyRoute =
  DashboardSettingsDisplayLazyRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/settings/display.lazy').then((d) => d.Route),
  )
const DashboardSettingsAppearanceLazyRoute =
  DashboardSettingsAppearanceLazyRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/settings/appearance.lazy').then((d) => d.Route),
  )
const DashboardSettingsAccountLazyRoute =
  DashboardSettingsAccountLazyRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/settings/account.lazy').then((d) => d.Route),
  )
const ShopProductsSlugRoute = ShopProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const AdminOutletsOutletIdRoute = AdminOutletsOutletIdRouteImport.update({
  id: '/outlets/$outletId',
  path: '/outlets/$outletId',
  getParentRoute: () => AdminRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/outlet': typeof OutletRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shop': typeof ShopRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/customer/sign-in': typeof CustomerSignInRoute
  '/customer/sign-up': typeof CustomerSignUpRoute
  '/customer/verify-email': typeof CustomerVerifyEmailRoute
  '/shop/about': typeof ShopAboutRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/contact': typeof ShopContactRoute
  '/shop/refund-policy': typeof ShopRefundPolicyRoute
  '/shop/shipping-policy': typeof ShopShippingPolicyRoute
  '/shop/terms': typeof ShopTermsRoute
  '/shop/wishlist': typeof ShopWishlistRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/outlet/': typeof OutletIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/outlets/$outletId': typeof AdminOutletsOutletIdRoute
  '/shop/products/$slug': typeof ShopProductsSlugRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountLazyRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceLazyRoute
  '/dashboard/settings/display': typeof DashboardSettingsDisplayLazyRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsLazyRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/coupons': typeof AdminCouponsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/offers': typeof AdminOffersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/outlets': typeof AdminOutletsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/shipments': typeof AdminShipmentsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/outlet/inventory': typeof OutletInventoryIndexRoute
  '/outlet/sales': typeof OutletSalesIndexRoute
  '/outlet/shipments': typeof OutletShipmentsIndexRoute
  '/outlet/sign-in': typeof OutletSignInIndexRoute
  '/shop/products': typeof ShopProductsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/customer/sign-in': typeof CustomerSignInRoute
  '/customer/sign-up': typeof CustomerSignUpRoute
  '/customer/verify-email': typeof CustomerVerifyEmailRoute
  '/shop/about': typeof ShopAboutRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/contact': typeof ShopContactRoute
  '/shop/refund-policy': typeof ShopRefundPolicyRoute
  '/shop/shipping-policy': typeof ShopShippingPolicyRoute
  '/shop/terms': typeof ShopTermsRoute
  '/shop/wishlist': typeof ShopWishlistRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/outlet': typeof OutletIndexRoute
  '/shop': typeof ShopIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/outlets/$outletId': typeof AdminOutletsOutletIdRoute
  '/shop/products/$slug': typeof ShopProductsSlugRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountLazyRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceLazyRoute
  '/dashboard/settings/display': typeof DashboardSettingsDisplayLazyRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsLazyRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/coupons': typeof AdminCouponsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/offers': typeof AdminOffersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/outlets': typeof AdminOutletsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/shipments': typeof AdminShipmentsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/outlet/inventory': typeof OutletInventoryIndexRoute
  '/outlet/sales': typeof OutletSalesIndexRoute
  '/outlet/shipments': typeof OutletShipmentsIndexRoute
  '/outlet/sign-in': typeof OutletSignInIndexRoute
  '/shop/products': typeof ShopProductsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/outlet': typeof OutletRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/shop': typeof ShopRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/customer/sign-in': typeof CustomerSignInRoute
  '/customer/sign-up': typeof CustomerSignUpRoute
  '/customer/verify-email': typeof CustomerVerifyEmailRoute
  '/shop/about': typeof ShopAboutRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/contact': typeof ShopContactRoute
  '/shop/refund-policy': typeof ShopRefundPolicyRoute
  '/shop/shipping-policy': typeof ShopShippingPolicyRoute
  '/shop/terms': typeof ShopTermsRoute
  '/shop/wishlist': typeof ShopWishlistRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/outlet/': typeof OutletIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/outlets/$outletId': typeof AdminOutletsOutletIdRoute
  '/shop/products/$slug': typeof ShopProductsSlugRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountLazyRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceLazyRoute
  '/dashboard/settings/display': typeof DashboardSettingsDisplayLazyRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsLazyRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/coupons/': typeof AdminCouponsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/offers/': typeof AdminOffersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/outlets/': typeof AdminOutletsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/shipments/': typeof AdminShipmentsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/outlet/inventory/': typeof OutletInventoryIndexRoute
  '/outlet/sales/': typeof OutletSalesIndexRoute
  '/outlet/shipments/': typeof OutletShipmentsIndexRoute
  '/outlet/sign-in/': typeof OutletSignInIndexRoute
  '/shop/products/': typeof ShopProductsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/outlet'
    | '/privacy-policy'
    | '/shop'
    | '/dashboard/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/account/addresses'
    | '/account/orders'
    | '/account/settings'
    | '/account/wishlist'
    | '/admin/sign-in'
    | '/customer/sign-in'
    | '/customer/sign-up'
    | '/customer/verify-email'
    | '/shop/about'
    | '/shop/cart'
    | '/shop/contact'
    | '/shop/refund-policy'
    | '/shop/shipping-policy'
    | '/shop/terms'
    | '/shop/wishlist'
    | '/account/'
    | '/admin/'
    | '/dashboard/'
    | '/outlet/'
    | '/shop/'
    | '/account/orders/$orderId'
    | '/admin/outlets/$outletId'
    | '/shop/products/$slug'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/outlets'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/shipments'
    | '/dashboard/settings/'
    | '/outlet/inventory'
    | '/outlet/sales'
    | '/outlet/shipments'
    | '/outlet/sign-in'
    | '/shop/products'
    | '/dashboard/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/privacy-policy'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/account/addresses'
    | '/account/orders'
    | '/account/settings'
    | '/account/wishlist'
    | '/admin/sign-in'
    | '/customer/sign-in'
    | '/customer/sign-up'
    | '/customer/verify-email'
    | '/shop/about'
    | '/shop/cart'
    | '/shop/contact'
    | '/shop/refund-policy'
    | '/shop/shipping-policy'
    | '/shop/terms'
    | '/shop/wishlist'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/outlet'
    | '/shop'
    | '/account/orders/$orderId'
    | '/admin/outlets/$outletId'
    | '/shop/products/$slug'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/offers'
    | '/admin/orders'
    | '/admin/outlets'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/shipments'
    | '/dashboard/settings'
    | '/outlet/inventory'
    | '/outlet/sales'
    | '/outlet/shipments'
    | '/outlet/sign-in'
    | '/shop/products'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/outlet'
    | '/privacy-policy'
    | '/shop'
    | '/dashboard/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/account/addresses'
    | '/account/orders'
    | '/account/settings'
    | '/account/wishlist'
    | '/admin/sign-in'
    | '/customer/sign-in'
    | '/customer/sign-up'
    | '/customer/verify-email'
    | '/shop/about'
    | '/shop/cart'
    | '/shop/contact'
    | '/shop/refund-policy'
    | '/shop/shipping-policy'
    | '/shop/terms'
    | '/shop/wishlist'
    | '/account/'
    | '/admin/'
    | '/dashboard/'
    | '/outlet/'
    | '/shop/'
    | '/account/orders/$orderId'
    | '/admin/outlets/$outletId'
    | '/shop/products/$slug'
    | '/dashboard/settings/account'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/display'
    | '/dashboard/settings/notifications'
    | '/admin/analytics/'
    | '/admin/categories/'
    | '/admin/coupons/'
    | '/admin/customers/'
    | '/admin/inventory/'
    | '/admin/offers/'
    | '/admin/orders/'
    | '/admin/outlets/'
    | '/admin/products/'
    | '/admin/settings/'
    | '/admin/shipments/'
    | '/dashboard/settings/'
    | '/outlet/inventory/'
    | '/outlet/sales/'
    | '/outlet/shipments/'
    | '/outlet/sign-in/'
    | '/shop/products/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OutletRoute: typeof OutletRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ShopRoute: typeof ShopRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  CustomerSignInRoute: typeof CustomerSignInRoute
  CustomerSignUpRoute: typeof CustomerSignUpRoute
  CustomerVerifyEmailRoute: typeof CustomerVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet': {
      id: '/outlet'
      path: '/outlet'
      fullPath: '/outlet'
      preLoaderRoute: typeof OutletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/outlet/': {
      id: '/outlet/'
      path: '/'
      fullPath: '/outlet/'
      preLoaderRoute: typeof OutletIndexRouteImport
      parentRoute: typeof OutletRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/shop/wishlist': {
      id: '/shop/wishlist'
      path: '/wishlist'
      fullPath: '/shop/wishlist'
      preLoaderRoute: typeof ShopWishlistRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/terms': {
      id: '/shop/terms'
      path: '/terms'
      fullPath: '/shop/terms'
      preLoaderRoute: typeof ShopTermsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/shipping-policy': {
      id: '/shop/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shop/shipping-policy'
      preLoaderRoute: typeof ShopShippingPolicyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/refund-policy': {
      id: '/shop/refund-policy'
      path: '/refund-policy'
      fullPath: '/shop/refund-policy'
      preLoaderRoute: typeof ShopRefundPolicyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/contact': {
      id: '/shop/contact'
      path: '/contact'
      fullPath: '/shop/contact'
      preLoaderRoute: typeof ShopContactRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/about': {
      id: '/shop/about'
      path: '/about'
      fullPath: '/shop/about'
      preLoaderRoute: typeof ShopAboutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/customer/verify-email': {
      id: '/customer/verify-email'
      path: '/customer/verify-email'
      fullPath: '/customer/verify-email'
      preLoaderRoute: typeof CustomerVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/sign-up': {
      id: '/customer/sign-up'
      path: '/customer/sign-up'
      fullPath: '/customer/sign-up'
      preLoaderRoute: typeof CustomerSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/sign-in': {
      id: '/customer/sign-in'
      path: '/customer/sign-in'
      fullPath: '/customer/sign-in'
      preLoaderRoute: typeof CustomerSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sign-in': {
      id: '/admin/sign-in'
      path: '/sign-in'
      fullPath: '/admin/sign-in'
      preLoaderRoute: typeof AdminSignInRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/shop/products/': {
      id: '/shop/products/'
      path: '/products'
      fullPath: '/shop/products'
      preLoaderRoute: typeof ShopProductsIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/outlet/sign-in/': {
      id: '/outlet/sign-in/'
      path: '/sign-in'
      fullPath: '/outlet/sign-in'
      preLoaderRoute: typeof OutletSignInIndexRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/shipments/': {
      id: '/outlet/shipments/'
      path: '/shipments'
      fullPath: '/outlet/shipments'
      preLoaderRoute: typeof OutletShipmentsIndexRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/sales/': {
      id: '/outlet/sales/'
      path: '/sales'
      fullPath: '/outlet/sales'
      preLoaderRoute: typeof OutletSalesIndexRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/inventory/': {
      id: '/outlet/inventory/'
      path: '/inventory'
      fullPath: '/outlet/inventory'
      preLoaderRoute: typeof OutletInventoryIndexRouteImport
      parentRoute: typeof OutletRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/admin/shipments/': {
      id: '/admin/shipments/'
      path: '/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AdminShipmentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/outlets/': {
      id: '/admin/outlets/'
      path: '/outlets'
      fullPath: '/admin/outlets'
      preLoaderRoute: typeof AdminOutletsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers/': {
      id: '/admin/offers/'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons/': {
      id: '/admin/coupons/'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsLazyRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/display': {
      id: '/dashboard/settings/display'
      path: '/display'
      fullPath: '/dashboard/settings/display'
      preLoaderRoute: typeof DashboardSettingsDisplayLazyRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/appearance': {
      id: '/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceLazyRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/account': {
      id: '/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountLazyRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/shop/products/$slug': {
      id: '/shop/products/$slug'
      path: '/products/$slug'
      fullPath: '/shop/products/$slug'
      preLoaderRoute: typeof ShopProductsSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/outlets/$outletId': {
      id: '/admin/outlets/$outletId'
      path: '/outlets/$outletId'
      fullPath: '/admin/outlets/$outletId'
      preLoaderRoute: typeof AdminOutletsOutletIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminSignInRoute: typeof AdminSignInRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOutletsOutletIdRoute: typeof AdminOutletsOutletIdRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCouponsIndexRoute: typeof AdminCouponsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
  AdminOffersIndexRoute: typeof AdminOffersIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminOutletsIndexRoute: typeof AdminOutletsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminShipmentsIndexRoute: typeof AdminShipmentsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSignInRoute: AdminSignInRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOutletsOutletIdRoute: AdminOutletsOutletIdRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCouponsIndexRoute: AdminCouponsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
  AdminOffersIndexRoute: AdminOffersIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminOutletsIndexRoute: AdminOutletsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminShipmentsIndexRoute: AdminShipmentsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsAccountLazyRoute: typeof DashboardSettingsAccountLazyRoute
  DashboardSettingsAppearanceLazyRoute: typeof DashboardSettingsAppearanceLazyRoute
  DashboardSettingsDisplayLazyRoute: typeof DashboardSettingsDisplayLazyRoute
  DashboardSettingsNotificationsLazyRoute: typeof DashboardSettingsNotificationsLazyRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsAccountLazyRoute: DashboardSettingsAccountLazyRoute,
    DashboardSettingsAppearanceLazyRoute: DashboardSettingsAppearanceLazyRoute,
    DashboardSettingsDisplayLazyRoute: DashboardSettingsDisplayLazyRoute,
    DashboardSettingsNotificationsLazyRoute:
      DashboardSettingsNotificationsLazyRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardUsersIndexLazyRoute: typeof DashboardUsersIndexLazyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardUsersIndexLazyRoute: DashboardUsersIndexLazyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OutletRouteChildren {
  OutletIndexRoute: typeof OutletIndexRoute
  OutletInventoryIndexRoute: typeof OutletInventoryIndexRoute
  OutletSalesIndexRoute: typeof OutletSalesIndexRoute
  OutletShipmentsIndexRoute: typeof OutletShipmentsIndexRoute
  OutletSignInIndexRoute: typeof OutletSignInIndexRoute
}

const OutletRouteChildren: OutletRouteChildren = {
  OutletIndexRoute: OutletIndexRoute,
  OutletInventoryIndexRoute: OutletInventoryIndexRoute,
  OutletSalesIndexRoute: OutletSalesIndexRoute,
  OutletShipmentsIndexRoute: OutletShipmentsIndexRoute,
  OutletSignInIndexRoute: OutletSignInIndexRoute,
}

const OutletRouteWithChildren =
  OutletRoute._addFileChildren(OutletRouteChildren)

interface ShopRouteChildren {
  ShopAboutRoute: typeof ShopAboutRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopContactRoute: typeof ShopContactRoute
  ShopRefundPolicyRoute: typeof ShopRefundPolicyRoute
  ShopShippingPolicyRoute: typeof ShopShippingPolicyRoute
  ShopTermsRoute: typeof ShopTermsRoute
  ShopWishlistRoute: typeof ShopWishlistRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductsSlugRoute: typeof ShopProductsSlugRoute
  ShopProductsIndexRoute: typeof ShopProductsIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAboutRoute: ShopAboutRoute,
  ShopCartRoute: ShopCartRoute,
  ShopContactRoute: ShopContactRoute,
  ShopRefundPolicyRoute: ShopRefundPolicyRoute,
  ShopShippingPolicyRoute: ShopShippingPolicyRoute,
  ShopTermsRoute: ShopTermsRoute,
  ShopWishlistRoute: ShopWishlistRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductsSlugRoute: ShopProductsSlugRoute,
  ShopProductsIndexRoute: ShopProductsIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OutletRoute: OutletRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ShopRoute: ShopRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  CustomerSignInRoute: CustomerSignInRoute,
  CustomerSignUpRoute: CustomerSignUpRoute,
  CustomerVerifyEmailRoute: CustomerVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
